spring:
    application.name: java-resilience4j
    jackson.serialization.indent_output: true

server:
    port: 9080

info:
    name: ${spring.application.name}
    description: resilience4j test
    environment: ${spring.profiles.active}
    version: 0.0.1

resilience4j.retry:
    configs:
        default:
            maxAttempts: 10
            waitDuration: 100
            retryExceptions:
                - org.springframework.web.client.ResourceAccessException
                - org.springframework.web.client.HttpServerErrorException
    instances:
        backenda:
            baseConfig: default

resilience4j.ratelimiter:
    configs:
        default:
            registerHealthIndicator: false
            limitForPeriod: 1
            limitRefreshPeriod: 10s
            timeoutDuration: 1s
            eventConsumerBufferSize: 100
    instances:
        internal:
            baseConfig: default